DeviceName: "Fake_Controller"

UpdateTime: 0.5 #Unit 1s

Broker:
    IP: "pihole.fritz.box"
    Port: 1883
    User:
    Password:

PLC:
    IP: "192.168.178.57"  # Only needed if script runs from linux device
    AMSNETID: "192.168.178.57.1.1"
    Mode : TC3

Data_TC2: #In TC2 only Memmory Variables are supported. f.e. MD4088 -> Offset 4088, Type: DINT
  - DisplayName: "Kommando"
    Offset: 4088
    Datatype: "UDINT"
    iot.Unit: '°C'
    iot.ReadOnly: true
    iot.MinValue: 0
    iot.MaxValue: 255
    iot.DecimalPrecision:
    
Data_TC3: #In TC3 only the destination string is needed. Like Main.bTest or GVL.udiRunTime
  - DisplayName: "Kommando"
    Path: "DOOCS_IF.Command"
    iot.Unit: "°C"
    iot.ReadOnly: false
    iot.MinValue: 0
    iot.MaxValue: 4
    iot.DecimalPrecision:

  - DisplayName: "LED"
    Path: "DOOCS_IF.bLED"
    iot.Unit: ""
    iot.ReadOnly: true
    iot.MinValue: 
    iot.MaxValue:
    iot.DecimalPrecision:

  - DisplayName: "Sollposition"
    Path: "DOOCS_IF.diSollposition"
    iot.Unit: "mm"
    iot.ReadOnly: false
    iot.MinValue:
    iot.MaxValue:
    iot.DecimalPrecision: