DeviceName: "Fake_Controller"

UpdateTime: 0.5 #Unit 1s

Broker:
    IP: "pihole.fritz.box"
    Port: 1883
    User:
    Password:

PLC:
    IP: "192.168.178.57"  # Only needed if script runs from linux device
    AMSNETID: "192.168.178.57.1.1"
    Mode : TC3

Data_TC2: #In TC2 only Memmory Variables are supported. f.e. MD4088 -> Offset 4088, Type: DINT
  - DisplayName: "Kommando"
    Offset: 4088
    Datatype: "UDINT"
    Unit: '°C'
    ReadOnly: true
    MinValue: 0
    MaxValue: 255
    DecimalPrecision:
    
Data_TC3: #In TC3 only the destination string is needed. Like Main.bTest or GVL.udiRunTime
  - DisplayName: "Kommando"
    Path: "DOOCS_IF.Command"
    Unit: "°C"
    ReadOnly: false
    MinValue: 0
    MaxValue: 4
    DecimalPrecision:

  - DisplayName: "LED"
    Path: "DOOCS_IF.bLED"
    Unit: ""
    ReadOnly: false
    MinValue: 
    MaxValue:
    DecimalPrecision:

  - DisplayName: "Sollposition"
    Path: "DOOCS_IF.diSollposition"
    Unit: "mm"
    ReadOnly: false
    MinValue:
    MaxValue:
    DecimalPrecision: